
/* Drop Tables */

DROP TABLE COMMENT_LIKE CASCADE CONSTRAINTS;
DROP TABLE TB_IMAGE CASCADE CONSTRAINTS;
DROP TABLE NEW_COMMENTS CASCADE CONSTRAINTS;
DROP TABLE TB_SUGGEST CASCADE CONSTRAINTS;
DROP TABLE TB_NEWS CASCADE CONSTRAINTS;
DROP TABLE NEWS_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE NEWS_TYPE CASCADE CONSTRAINTS;
DROP TABLE TB_NEWS_SIGN CASCADE CONSTRAINTS;
DROP TABLE REPORTER_EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE REPORTER_DEPT CASCADE CONSTRAINTS;
DROP TABLE TB_AD CASCADE CONSTRAINTS;
DROP TABLE TB_CITIZEN_IMG CASCADE CONSTRAINTS;
DROP TABLE TB_CITIZEN_REPORT CASCADE CONSTRAINTS;
DROP TABLE TB_USER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE COMMENT_LIKE
(
	COMMENT_PREFERENCE char CONSTRAINT COMMENT_PREFERENCE_CK CHECK (COMMENT_PREFERENCE IN ('Y','N')),
	COMMENT_NO number(10,0) NOT NULL,
	USER_NO number(7,0) NOT NULL,
	CONSTRAINT UNIQUE_COMMENT_KEY UNIQUE (COMMENT_NO, USER_NO)
);


CREATE TABLE NEWS_CATEGORY
(
	CATEGORY_NO number(3) NOT NULL,
	CATEGORY_NAME varchar2(20),
	PRIMARY KEY (CATEGORY_NO)
);


CREATE TABLE NEWS_TYPE
(
	NEWS_TYPE_NO number(3) NOT NULL,
	NEWS_TYPE_NAME varchar2(20),
	PRIMARY KEY (NEWS_TYPE_NO)
);


CREATE TABLE NEWS_COMMENTS
(
	COMMENT_NO number(10,0) NOT NULL,
	COMMENT_REGDATE date,
	NEWS_NO number(10,0) NOT NULL,
	USER_NO number(7,0) NOT NULL,
	PRIMARY KEY (COMMENT_NO)
);


CREATE TABLE REPORTER_DEPT
(
	DEPT_NO number(5,0) NOT NULL,
	DEPT_NAME varchar2(30),
	PRIMARY KEY (DEPT_NO)
);


CREATE TABLE REPORTER_EMPLOYEE
(
	REPORTER_NO number(7,0) NOT NULL,
	REPORTER_ID varchar2(50),
	REPORTER_NAME varchar2(20),
	REPORTER_POS varchar2(10),
	REPORTER_EMAIL varchar2(100),
	REPORTER_PHONE varchar2(13),
	REPORTER_PW char(64),
	DEPT_NO number(5,0) NOT NULL,
	PRIMARY KEY (REPORTER_NO)
);


CREATE TABLE TB_AD
(
	AD_NO number(7,0) NOT NULL,
	AD_IMG_PATH varchar2(300),
	AD_LINK varchar2(400),
	AD_START_DATE date,
	AD_END_DATE date,
	PRIMARY KEY (AD_NO)
);


CREATE TABLE TB_CITIZEN_IMG
(
	CR_IMG_NO number(7,0) NOT NULL,
	CR_IMG_PATH varchar2(300),
	CR_NO number(7,0) NOT NULL,
	PRIMARY KEY (CR_IMG_NO)
);


CREATE TABLE TB_CITIZEN_REPORT
(
	CR_NO number(7,0) NOT NULL,
	CR_TITLE varchar2(500),
	CR_CONTENTS long,
	CR_REGDATE date,
	PRIMARY KEY (CR_NO)
);


CREATE TABLE TB_IMAGE
(
	IMG_NO number(4,0) NOT NULL,
	IMG_LOCATION varchar2(100),
	IMG_TITLE varchar2(300),
	IMG_ALT varchar2(100),
	IMG_PATH varchar2(300),
	IMG_ALTER_STATE char(1) CONSTRAINT IMG_ALTER_STATE_CK CHECK (IMG_ALTER_STATE IN ('Y','N')),
	REPORTER_NO number(7,0) NOT NULL,
	NEWS_TYPE_NO number(3) NOT NULL,
	CATEGORY_NO number(3) NOT NULL,
	IMG_REGDATE date,
	PRIMARY KEY (IMG_NO)
);


CREATE TABLE TB_NEWS
(
	NEWS_NO number(10,0) NOT NULL,
	NEWS_LOCATION varchar2(50),
	NEWS_TITLE varchar2(300),
	NEWS_CONTENTS long,
	NEWS_REGDATE date,
	NEWS_IMG_PATH varchar2(300),
	NEWS_VIEW_CNT number(10,0),
	NEWS_SIGN_STATE char CONSTRAINT NEWS_SIGN_STATE_CK CHECK (NEWS_SIGN_STATE IN ('Y','N')),
	NEWS_TYPE_NO number(3) NOT NULL,
	CATEGORY_NO number(3) NOT NULL,
	REPORTER_NO number(7,0) NOT NULL,
	PRIMARY KEY (NEWS_NO)
);


CREATE TABLE TB_NEWS_SIGN
(
	FIRST_SIGN_STATE char(1) CONSTRAINT FIRST_SIGN_STATE_CK CHECK (FIRST_SIGN_STATE IN ('Y','N')),
	SECOND_SIGN_STATE char(1) CONSTRAINT SECOND_SIGN_STATE_CK CHECK (SECOND_SIGN_STATE IN ('Y','N')),
	FIRST_SIGNER_NO number(7,0) NOT NULL ,
	SECOND_SIGNER_NO number(7,0) NOT NULL
);


CREATE TABLE TB_SUGGEST
(
	NEWS_NO number(10,0) NOT NULL,
	USER_NO number(7,0) NOT NULL
);


CREATE TABLE TB_USER
(
	USER_NO number(7,0) NOT NULL,
	USER_ID varchar2(100),
	USER_PW char(64),
	USER_NAME varchar2(20),
	USER_EMAIL varchar2(100),
	USER_PW_QUESTION varchar2(1000),
	USER_PW_ANSWER varchar2(1000),
	PRIMARY KEY (USER_NO)
);



/* Create Foreign Keys */

ALTER TABLE TB_IMAGE
	ADD FOREIGN KEY (CATEGORY_NO)
	REFERENCES NEWS_CATEGORY (CATEGORY_NO)
;


ALTER TABLE TB_NEWS
	ADD FOREIGN KEY (CATEGORY_NO)
	REFERENCES NEWS_CATEGORY (CATEGORY_NO)
;


ALTER TABLE TB_IMAGE
	ADD FOREIGN KEY (NEWS_TYPE_NO)
	REFERENCES NEWS_TYPE (NEWS_TYPE_NO)
;


ALTER TABLE TB_NEWS
	ADD FOREIGN KEY (NEWS_TYPE_NO)
	REFERENCES NEWS_TYPE (NEWS_TYPE_NO)
;


ALTER TABLE COMMENT_LIKE
	ADD FOREIGN KEY (COMMENT_NO)
	REFERENCES NEW_COMMENTS (COMMENT_NO)
;


ALTER TABLE REPORTER_EMPLOYEE
	ADD FOREIGN KEY (DEPT_NO)
	REFERENCES REPORTER_DEPT (DEPT_NO)
;


ALTER TABLE TB_IMAGE
	ADD FOREIGN KEY (REPORTER_NO)
	REFERENCES REPORTER_EMPLOYEE (REPORTER_NO)
;


ALTER TABLE TB_NEWS
	ADD FOREIGN KEY (REPORTER_NO)
	REFERENCES REPORTER_EMPLOYEE (REPORTER_NO)
;


ALTER TABLE TB_NEWS_SIGN
	ADD FOREIGN KEY (FIRST_SIGNER_NO)
	REFERENCES REPORTER_EMPLOYEE (REPORTER_NO)
;


ALTER TABLE TB_NEWS_SIGN
	ADD FOREIGN KEY (SECOND_SIGNER_NO)
	REFERENCES REPORTER_EMPLOYEE (REPORTER_NO)
;


ALTER TABLE TB_CITIZEN_IMG
	ADD FOREIGN KEY (CR_NO)
	REFERENCES TB_CITIZEN_REPORT (CR_NO)
;


ALTER TABLE NEW_COMMENTS
	ADD FOREIGN KEY (NEWS_NO)
	REFERENCES TB_NEWS (NEWS_NO)
;


ALTER TABLE TB_SUGGEST
	ADD FOREIGN KEY (NEWS_NO)
	REFERENCES TB_NEWS (NEWS_NO)
;


ALTER TABLE COMMENT_LIKE
	ADD FOREIGN KEY (USER_NO)
	REFERENCES TB_USER (USER_NO)
;


ALTER TABLE NEW_COMMENTS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES TB_USER (USER_NO)
;


ALTER TABLE TB_SUGGEST
	ADD FOREIGN KEY (USER_NO)
	REFERENCES TB_USER (USER_NO)
;



